#!/bin/bash
#
# NanoClaw backup script
#
# Strategy: back up everything not in Git and not regenerated.
# New files are automatically included — only update EXCLUDES if
# something new is transient/regenerated.
#
# Run manually or via cron/systemd timer.
# Uses rsync with hardlinks to previous backup for deduplication.
#

set -euo pipefail

NANOCLAW_DIR="/home/jihartik/nanoclaw"
BACKUP_ROOT="/home/jihartik/nanoclaw-backups"
KEEP_COUNT=7  # Number of backups to retain
TIMESTAMP=$(date +%Y%m%d-%H%M%S)
BACKUP_DIR="${BACKUP_ROOT}/${TIMESTAMP}"

# External paths to include (these live outside the project dir)
EXTERNAL_PATHS=(
  "$HOME/.local/share/signal-cli"                                # Signal identity & encryption keys
  "$HOME/.config/nanoclaw"                                       # Mount/sender allowlists + api-tokens.json
  "$HOME/.config/gws"                                            # Google Workspace CLI encrypted creds + AES key
  "$HOME/.ssh/nanoclaw_deploy"                                   # GitHub deploy key (private)
  "$HOME/.ssh/nanoclaw_deploy.pub"                               # GitHub deploy key (public)
  "$HOME/.claude/plans"                                          # Claude Code plan files
  "$HOME/.claude/projects/-home-jihartik-nanoclaw/memory"        # Claude Code per-project memory
)

# Excludes: Git-tracked files, regenerated files, and transient data.
#
# Git-tracked files are excluded automatically by generating an exclude
# list from `git ls-files`. Only untracked, non-gitignored files are backed up.
#
# v2 layout (post-migration):
#   data/v2.db                                       — central DB (BACK UP)
#   data/v2-sessions/<group_id>/.claude-shared/       — per-group Claude state
#   data/v2-sessions/<group_id>/<session_id>/         — per-session inbound.db + outbound.db (BACK UP)
RSYNC_EXCLUDES=(
  # Git internals
  ".git/"
  # Build artifacts & dependencies (restored by pnpm install + pnpm run build)
  "node_modules/"
  "dist/"
  # Test coverage reports (regenerated by vitest --coverage)
  "coverage/"
  # Transient runtime files
  "logs/"
  # Husky git hooks (regenerated by pnpm install)
  ".husky/_/"
  # Per-session heartbeat (touched continuously; cheap to recreate)
  "data/v2-sessions/*/*/.heartbeat"
  # Per-group .claude-shared session artifacts (low value, regenerated or ephemeral)
  "data/v2-sessions/*/.claude-shared/backups/"
  "data/v2-sessions/*/.claude-shared/shell-snapshots/"
  "data/v2-sessions/*/.claude-shared/plugins/"
  "data/v2-sessions/*/.claude-shared/skills/"
  "data/v2-sessions/*/.claude-shared/projects/*/subagents/"
  "data/v2-sessions/*/.claude-shared/projects/*/tool-results/"
  # Composed CLAUDE.md artifacts (regenerated every spawn)
  "groups/*/CLAUDE.md"
  "groups/*/.claude-shared.md"
  "groups/*/.claude-fragments/"
)

# Auto-exclude all Git-tracked files (they're restored by git clone)
# Prefix each path with / so rsync matches from the root only
# (prevents "CLAUDE.md" from matching "groups/*/CLAUDE.md")
GIT_EXCLUDE_FILE=$(mktemp)
trap "rm -f '$GIT_EXCLUDE_FILE'" EXIT
(cd "$NANOCLAW_DIR" && git ls-files | sed 's|^|/|') > "$GIT_EXCLUDE_FILE"

# --- Sanity checks ---

# Warn if any external path is missing
for path in "${EXTERNAL_PATHS[@]}"; do
  if [ ! -e "$path" ]; then
    echo "WARNING: External path not found: $path" >&2
  fi
done

# --- Create backup ---

mkdir -p "$BACKUP_ROOT"

# Find the latest existing backup for hardlink deduplication. rsync's
# --link-dest is interpreted relative to the *destination*, so each
# rsync below builds its own link-dest pointing at the matching
# subtree under "$LATEST" (project/ for the project rsync, external/<rel>
# for each external path).
LATEST=$(ls -1d "${BACKUP_ROOT}"/[0-9]* 2>/dev/null | sort | tail -1 || true)
HAS_LATEST=""
if [ -n "$LATEST" ] && [ -d "$LATEST" ]; then
  HAS_LATEST=1
fi

# Build rsync exclude args
EXCLUDE_ARGS=()
for pattern in "${RSYNC_EXCLUDES[@]}"; do
  EXCLUDE_ARGS+=(--exclude="$pattern")
done

# Backup project directory (non-Git, non-regenerated files)
echo "Backing up NanoClaw project..."
mkdir -p "${BACKUP_DIR}/project"
rsync -a ${HAS_LATEST:+--link-dest="${LATEST}/project"} "${EXCLUDE_ARGS[@]}" \
  --exclude-from="$GIT_EXCLUDE_FILE" \
  "${NANOCLAW_DIR}/" "${BACKUP_DIR}/project/"

# Backup external paths
echo "Backing up external paths..."
mkdir -p "${BACKUP_DIR}/external"
for path in "${EXTERNAL_PATHS[@]}"; do
  if [ -e "$path" ]; then
    # Preserve directory structure relative to home
    rel_path="${path#$HOME/}"
    dest_dir="${BACKUP_DIR}/external/$(dirname "$rel_path")"
    mkdir -p "$dest_dir"
    rsync -a ${HAS_LATEST:+--link-dest="${LATEST}/external/$(dirname "$rel_path")"} \
      "$path" "$dest_dir/" 2>/dev/null || \
    rsync -a "$path" "$dest_dir/"
  fi
done

# --- Prune old backups ---

BACKUP_COUNT=$(ls -1d "${BACKUP_ROOT}"/[0-9]* 2>/dev/null | wc -l)
if [ "$BACKUP_COUNT" -gt "$KEEP_COUNT" ]; then
  echo "Pruning old backups (keeping ${KEEP_COUNT})..."
  ls -1d "${BACKUP_ROOT}"/[0-9]* | sort | head -n -${KEEP_COUNT} | while read old; do
    rm -rf "$old"
    echo "  Removed: $(basename "$old")"
  done
fi

# --- Summary ---

BACKUP_SIZE=$(du -sh "${BACKUP_DIR}" | cut -f1)
echo ""
echo "Backup complete: ${BACKUP_DIR} (${BACKUP_SIZE})"
echo "Backups retained: $(ls -1d "${BACKUP_ROOT}"/[0-9]* | wc -l)/${KEEP_COUNT}"
