#!/bin/bash
#
# NanoClaw backup script
#
# Strategy: back up everything not in Git and not regenerated.
# New files are automatically included — only update EXCLUDES if
# something new is transient/regenerated.
#
# Run manually or via cron/systemd timer.
# Uses rsync with hardlinks to previous backup for deduplication.
#

set -euo pipefail

NANOCLAW_DIR="/home/jihartik/nanoclaw"
BACKUP_ROOT="/home/jihartik/nanoclaw-backups"
KEEP_COUNT=7  # Number of backups to retain
TIMESTAMP=$(date +%Y%m%d-%H%M%S)
BACKUP_DIR="${BACKUP_ROOT}/${TIMESTAMP}"

# External paths to include (these live outside the project dir)
EXTERNAL_PATHS=(
  "$HOME/.local/share/signal-cli"                                # Signal identity & encryption keys
  "$HOME/.config/nanoclaw"                                       # Mount/sender allowlists
  "$HOME/.ssh/nanoclaw_deploy"                                   # GitHub deploy key (private)
  "$HOME/.ssh/nanoclaw_deploy.pub"                               # GitHub deploy key (public)
  "$HOME/.claude/plans"                                          # Claude Code plan files
  "$HOME/.claude/projects/-home-jihartik-nanoclaw/memory"        # Claude Code per-project memory
)

# Excludes: Git-tracked files, regenerated files, and transient data
#
# Git-tracked files are excluded automatically by generating an exclude
# list from `git ls-files`. Only untracked, non-gitignored files are backed up.
RSYNC_EXCLUDES=(
  # Git internals
  ".git/"
  # Build artifacts & dependencies (restored by npm install + npm run build)
  "node_modules/"
  "dist/"
  # Test coverage reports (regenerated by vitest --coverage)
  "coverage/"
  # Regenerated on every container start by container-runner.ts
  "data/sessions/*/.claude/settings.json"
  "groups/*/.mcp.json"
  # Transient runtime files
  "data/ipc/"
  "logs/"
  # Husky git hooks (regenerated by npm install)
  ".husky/_/"
  # Session artifacts (low value, regenerated or ephemeral)
  "data/sessions/*/.claude/backups/"
  "data/sessions/*/.claude/shell-snapshots/"
  "data/sessions/*/.claude/plugins/"
  "data/sessions/*/agent-runner-src/"
  "data/sessions/*/.claude/skills/"
  "data/sessions/*/.claude/projects/*/subagents/"
  "data/sessions/*/.claude/projects/*/tool-results/"
)

# Auto-exclude all Git-tracked files (they're restored by git clone)
# Prefix each path with / so rsync matches from the root only
# (prevents "CLAUDE.md" from matching "groups/*/CLAUDE.md")
GIT_EXCLUDE_FILE=$(mktemp)
trap "rm -f '$GIT_EXCLUDE_FILE'" EXIT
(cd "$NANOCLAW_DIR" && git ls-files | sed 's|^|/|') > "$GIT_EXCLUDE_FILE"

# --- Sanity checks ---

# Warn if any external path is missing
for path in "${EXTERNAL_PATHS[@]}"; do
  if [ ! -e "$path" ]; then
    echo "WARNING: External path not found: $path" >&2
  fi
done

# --- Create backup ---

mkdir -p "$BACKUP_ROOT"

# Find the latest existing backup for hardlink deduplication
LATEST=$(ls -1d "${BACKUP_ROOT}"/[0-9]* 2>/dev/null | sort | tail -1 || true)
LINK_DEST=""
if [ -n "$LATEST" ] && [ -d "$LATEST" ]; then
  LINK_DEST="--link-dest=${LATEST}"
fi

# Build rsync exclude args
EXCLUDE_ARGS=()
for pattern in "${RSYNC_EXCLUDES[@]}"; do
  EXCLUDE_ARGS+=(--exclude="$pattern")
done

# Backup project directory (non-Git, non-regenerated files)
echo "Backing up NanoClaw project..."
mkdir -p "${BACKUP_DIR}/project"
rsync -a ${LINK_DEST} "${EXCLUDE_ARGS[@]}" \
  --exclude-from="$GIT_EXCLUDE_FILE" \
  "${NANOCLAW_DIR}/" "${BACKUP_DIR}/project/"

# Backup external paths
echo "Backing up external paths..."
mkdir -p "${BACKUP_DIR}/external"
for path in "${EXTERNAL_PATHS[@]}"; do
  if [ -e "$path" ]; then
    # Preserve directory structure relative to home
    rel_path="${path#$HOME/}"
    dest_dir="${BACKUP_DIR}/external/$(dirname "$rel_path")"
    mkdir -p "$dest_dir"
    rsync -a ${LINK_DEST:+--link-dest="${LATEST}/external/$(dirname "$rel_path")"} \
      "$path" "$dest_dir/" 2>/dev/null || \
    rsync -a "$path" "$dest_dir/"
  fi
done

# --- Prune old backups ---

BACKUP_COUNT=$(ls -1d "${BACKUP_ROOT}"/[0-9]* 2>/dev/null | wc -l)
if [ "$BACKUP_COUNT" -gt "$KEEP_COUNT" ]; then
  echo "Pruning old backups (keeping ${KEEP_COUNT})..."
  ls -1d "${BACKUP_ROOT}"/[0-9]* | sort | head -n -${KEEP_COUNT} | while read old; do
    rm -rf "$old"
    echo "  Removed: $(basename "$old")"
  done
fi

# --- Summary ---

BACKUP_SIZE=$(du -sh "${BACKUP_DIR}" | cut -f1)
echo ""
echo "Backup complete: ${BACKUP_DIR} (${BACKUP_SIZE})"
echo "Backups retained: $(ls -1d "${BACKUP_ROOT}"/[0-9]* | wc -l)/${KEEP_COUNT}"
